apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-dev
  namespace: ns-dev
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-dev
  namespace: ns-dev
subjects:
  - kind: User
    name: course22
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-dev
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  namespace: ns-dev
spec:
  containers:
    - name: web
      image: nginx:alpine
