apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods
subjects:
  - kind: Group
    name: developers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  namespace: ns-dev
spec:
  containers:
    - name: web
      image: nginx:alpine
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-parameters
  namespace: ns-dev
data:
  domain: https://dev-api.company.com
  apiUrl: /api/v1
