apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: sm-parameters
  namespace: ns-dev
data:
  dbHost: ZGF0YWJhc2UtaW5zdGFuY2UwMS5teWNvbXBhbnkuY29tCg==
  dbPort: MzMwNgo=
  dbUser: dXNlci1kYgo=
  dbPass: M2xHaWdhbnRlMjAyOSMK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ns-dev
  labels:
    env: dev
    app: frontend
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: web
          image: python:3.6-alpine
          command:
            [
              "sh",
              "-c",
              "echo 'Home from Python container' > index.html && python -m http.server 9000",
            ]
          env:
            - name: TITLE
              value: "Welcome to the Frontend"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: sm-parameters
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: sm-parameters
                  key: dbPort
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: sm-parameters
                  key: dbUser
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: sm-parameters
                  key: dbPass
