apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-parameters
  namespace: ns-dev
data:
  domain: https://dev-api.company.com
  apiUrlVersion: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ns-dev
  labels:
    env: dev
    app: frontend
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: web
          image: python:3.6-alpine
          command:
            [
              "sh",
              "-c",
              "echo 'Home from Python container' > index.html && python -m http.server 9000",
            ]
          env:
            - name: TITLE
              value: "Welcome to the Frontend"
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-parameters
                  key: domain
            - name: API_URL_VERSION
              valueFrom:
                configMapKeyRef:
                  name: cm-parameters
                  key: apiUrlVersion
