apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-memory-cpu
  namespace: ns-dev
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 1
      defaultRequest:
        memory: 256Mi
        cpu: 0.5
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  namespace: ns-dev
spec:
  containers:
    - name: web
      image: nginx:alpine
