apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    env: dev
    app: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: web
          image: python:3.7-alpine
          command:
            [
              "sh",
              "-c",
              "echo 'Home from Python container' > index.html && python -m http.server 9000",
            ]
